### ISSUE TITLE
joal-desktop, unable to seed a torrent

### ISSUE THREAD

**Issue by smed79** [anthonyraymond/joal-desktop#99]
Hey,
I am unable to make joal seed a torrent.
when adding a torrent, joal check the file then delete it (see the screen record).

Someone can help investigating this issue... Thanks in advance.

```
$ cat /etc/lsb-release
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.1.0
DISTRIB_CODENAME=Talos
DISTRIB_DESCRIPTION="Manjaro Linux"
```

```
$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```
``` 
$ ./JoalDesktop.AppImage
Checking for update
Update for version 2.0.16 is not available (latest version: 2.0.16, downgrade is disallowed).
ELECTRON: done updating, no updates available
Asked to install jre
Jre is already installed and does not needs to update
Asked to install joal
Joal is already installed and does not needs to update
JRE: done updating, no updates available
JOAL: done updating, no updates available
All updates done
Start joal now
Running joal with config:  { host: '127.0.0.1',
  port: 5081,
  pathPrefix: '********-****-****-****-************',
  secretToken: '********-****-****-****-************' }
```

https://user-images.githubusercontent.com/1873139/230336425-a30a7087-35e5-4cc9-b0ab-80e38e3b75e6.mp4

**Comment by smed79** [comment]
The command line version output the error message
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: 
org/araymond/joal/JackOfAllTradesApplication has been compiled by a more recent 
version of the Java Runtime (class file version 55.0), this version of the Java Runtime 
only recognizes class file versions up to 52.0

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

**Comment by smed79** [comment]
The issue with command line version is now fixed by installing `jre11-openjdk` and witching to version **11**

`$ sudo pacman -S jre11-openjdk`

`$ sudo archlinux-java set java-11-openjdk`

```
$ archlinux-java status
Available Java environments:
  java-11-openjdk (default)
  java-8-openjdk/jre
```

... Remains the problem described in the [first post](https://github.com/anthonyraymond/joal-desktop/issues/99#issue-1657053377).

**Comment by anthonyraymond** [comment]
Hi, indeed the message was telling you that you were needing to install java 11+. Not sure why though, since joal-desktop should download his own JRE anyway...


For your problem, most of the time is because of :
- The torrent is too old (the tracker may have changed his address and you need to re-download the torrent file)
- Joal-Desktop can't talk with the tracker (no network, DNS blocked by your ISP)

Can you double check those?
